/**
 * Created with JetBrains WebStorm.
 * User: santiago
 * Date: 15/09/13
 * Time: 14:11
 * To change this template use File | Settings | File Templates.
 */
var a = { resource: '/orders/789033087',
    user_id: '77169310',
    topic: 'orders',
    application_id: 4416176012263899,
    attempts: 1,
    sent: '2013-09-15T17:09:40.194Z',
    received: '2013-09-15T17:09:40.166Z',
    info: { id: 789033087,
        status: 'confirmed',
        status_detail: null,
        date_created: '2013-09-15T13:09:37.000-04:00',
        date_closed: '2013-09-15T13:09:37.000-04:00',
        order_items: [
            [Object]
        ],
        total_amount: 1500,
        currency_id: 'ARS',
        buyer: { id: 145789457,
            nickname: 'SANTIAGONAHUELCORDOBA',
            email: 'scordob.l75lc7@mail.mercadolibre.com',
            phone: [Object],
            first_name: 'Santiago Nahuel',
            last_name: 'Cordoba',
            billing_info: [Object] },
        seller: { id: 77169310,
            nickname: 'SANTI8AGO8',
            email: 'scordob.ypnrwq@mail.mercadolibre.com',
            phone: [Object],
            first_name: 'Santiago',
            last_name: 'Córdoba' },
        payments: [],
        feedback: { sale: null, purchase: null },
        shipping: { status: 'to_be_agreed' },
        tags: [ 'not_delivered', 'not_paid' ] },
    item: { id: 'MLA476380215',
        site_id: 'MLA',
        title: 'Jaula Animal',
        subtitle: null,
        seller_id: 77169310,
        category_id: 'MLA1102',
        price: 1500,
        base_price: 1500,
        currency_id: 'ARS',
        initial_quantity: 2,
        available_quantity: 1,
        sold_quantity: 1,
        buying_mode: 'buy_it_now',
        listing_type_id: 'free',
        start_time: '2013-09-15T17:08:00.000Z',
        stop_time: '2013-09-22T17:08:00.000Z',
        condition: 'new',
        permalink: 'http://articulo.mercadolibre.com.ar/MLA-476380215-jaula-animal-_JM',
        thumbnail: 'http://img2.mlstatic.com/s_MLA_v_I_f_5035619899_092013.jpg',
        secure_thumbnail: 'https://www.mercadolibre.com/jm/img?s=MLA&v=I&f=5035619899_092013.jpg',
        pictures: [
            [Object]
        ],
        video_id: null,
        descriptions: [],
        accepts_mercadopago: false,
        non_mercado_pago_payment_methods: [
            [Object],
            [Object]
        ],
        shipping: { profile_id: null,
            mode: 'not_specified',
            local_pick_up: false,
            free_shipping: false,
            methods: [],
            dimensions: null },
        seller_address: { id: 5100041,
            comment: '',
            address_line: '',
            zip_code: '',
            city: [Object],
            state: [Object],
            country: [Object],
            latitude: '',
            longitude: '' },
        seller_contact: null,
        location: null,
        geolocation: { latitude: '', longitude: '' },
        coverage_areas: [],
        attributes: [],
        listing_source: '',
        variations: [],
        status: 'active',
        sub_status: [],
        tags: [],
        warranty: null,
        catalog_product_id: null,
        parent_item_id: null,
        automatic_relist: false,
        date_created: '2013-09-15T17:03:53.000Z',
        last_updated: '2013-09-15T17:09:37.000Z' },
    user: { id: 145789457,
        nickname: 'SANTIAGONAHUELCORDOBA',
        registration_date: '2013-09-15T05:17:57.000-04:00',
        country_id: 'AR',
        address: { state: null, city: null },
        user_type: 'normal',
        tags: [ 'normal' ],
        logo: null,
        points: 0,
        site_id: 'MLA',
        permalink: 'http://perfil.mercadolibre.com.ar/SANTIAGONAHUELCORDOBA',
        seller_reputation: { level_id: null,
            power_seller_status: null,
            transactions: [Object] },
        status: { site_status: 'active' } } }